using System.IO;
using System.Net;
using System.Net.Sockets;
using System.Text;
using System.Text.Json;

namespace BalancePet.Wpf.Services;

/// <summary>
/// Receives a one-time browser-extension session handoff over loopback only.
/// The bridge never binds to a LAN address and every request must include the
/// short-lived pairing code generated by the settings window.
/// </summary>
public sealed class BrowserSessionBridgeServer : IDisposable
{
    public const int Port = 28571;
    private const int MaxHeaderBytes = 16 * 1024;
    private const int MaxBodyBytes = 2 * 1024 * 1024;
    private readonly object _gate = new();
    private readonly CancellationTokenSource _shutdown = new();
    private TcpListener? _listener;
    private Task? _acceptLoop;
    private PairingState? _pairing;
    private bool _disposed;

    public event EventHandler<BrowserSessionReceivedEventArgs>? SessionReceived;

    public BrowserPairingInfo StartPairing(string profileId, string siteUrl)
    {
        if (_disposed) throw new ObjectDisposedException(nameof(BrowserSessionBridgeServer));
        if (!Uri.TryCreate(siteUrl, UriKind.Absolute, out var uri) || uri.Scheme is not ("http" or "https"))
            throw new InvalidOperationException("中转站地址无效。");

        lock (_gate)
        {
            EnsureListenerStarted();
            var code = Random.Shared.Next(100000, 999999).ToString(System.Globalization.CultureInfo.InvariantCulture);
            _pairing = new PairingState(profileId, uri.Host.TrimStart('.').ToLowerInvariant(), code, DateTimeOffset.UtcNow.AddMinutes(10));
            return new BrowserPairingInfo(code, uri.Host, Port, _pairing.ExpiresAt);
        }
    }

    private void EnsureListenerStarted()
    {
        if (_listener is not null) return;
        _listener = new TcpListener(IPAddress.Loopback, Port);
        _listener.Start();
        _acceptLoop = AcceptLoopAsync(_shutdown.Token);
    }

    private async Task AcceptLoopAsync(CancellationToken cancellationToken)
    {
        while (!cancellationToken.IsCancellationRequested)
        {
            TcpClient client;
            try { client = await _listener!.AcceptTcpClientAsync(cancellationToken); }
            catch (OperationCanceledException) when (cancellationToken.IsCancellationRequested) { break; }
            catch (ObjectDisposedException) { break; }
            catch (SocketException) when (cancellationToken.IsCancellationRequested) { break; }
            catch (SocketException) { continue; }
            _ = Task.Run(() => HandleClientAsync(client, cancellationToken), cancellationToken);
        }
    }

    private async Task HandleClientAsync(TcpClient client, CancellationToken cancellationToken)
    {
        using var clientScope = client;
        await using var stream = client.GetStream();
        try
        {
            var request = await ReadRequestAsync(stream, cancellationToken);
            if (request is null)
            {
                await WriteResponseAsync(stream, 400, "请求格式无效。", cancellationToken);
                return;
            }
            if (request.Method.Equals("OPTIONS", StringComparison.OrdinalIgnoreCase))
            {
                await WriteResponseAsync(stream, 204, "", cancellationToken);
                return;
            }
            if (!request.Method.Equals("POST", StringComparison.OrdinalIgnoreCase)
                || !request.Path.Equals("/v1/session", StringComparison.OrdinalIgnoreCase))
            {
                await WriteResponseAsync(stream, 404, "接口不存在。", cancellationToken);
                return;
            }
            // Browser extensions conventionally emit lower camel-case JSON
            // fields. Accept that wire format without weakening any of the
            // pairing/host checks below.
            var payload = JsonSerializer.Deserialize<BridgePayload>(request.Body, JsonOptions);
            PairingState? pairing;
            lock (_gate) pairing = _pairing;
            if (pairing is null || pairing.ExpiresAt < DateTimeOffset.UtcNow
                || payload is null
                || !CryptographicEquals(pairing.Code, payload.Code)
                || !HostMatches(pairing.SiteHost, payload.Host))
            {
                await WriteResponseAsync(stream, 403, "配对码无效、已过期或站点不匹配。", cancellationToken);
                return;
            }

            var cookies = payload.Cookies?
                .Where(cookie => !string.IsNullOrWhiteSpace(cookie.Name) && cookie.Name.Length <= 256 && cookie.Value is not null)
                .Take(512)
                .ToArray() ?? Array.Empty<BridgeCookie>();
            var header = string.Join("; ", cookies.Select(cookie => $"{cookie.Name.Trim()}={cookie.Value}"));
            var storage = payload.Storage?
                .Where(entry => !string.IsNullOrWhiteSpace(entry.Key)
                    && entry.Key.Length <= 256
                    && entry.Value is not null
                    && entry.Value.Length <= MaxBodyBytes)
                .Where(entry => entry.Key.Contains("session", StringComparison.OrdinalIgnoreCase)
                    || entry.Key.Contains("token", StringComparison.OrdinalIgnoreCase)
                    || entry.Key.Contains("auth", StringComparison.OrdinalIgnoreCase)
                    || entry.Key.Contains("credential", StringComparison.OrdinalIgnoreCase))
                .Take(32)
                .ToArray() ?? Array.Empty<BridgeStorageEntry>();
            if (header.Length == 0 && storage.Length > 0)
            {
                // Some relays keep the websee-session value in localStorage
                // instead of a browser Cookie. Preserve the storage key so a
                // relay expecting a named session cookie can use it directly.
                var preferred = storage.FirstOrDefault(entry => entry.Key.Equals("websee-session", StringComparison.OrdinalIgnoreCase))
                    ?? storage.FirstOrDefault(entry => entry.Key.Equals("session", StringComparison.OrdinalIgnoreCase))
                    ?? storage.First();
                header = $"{preferred.Key.Trim()}={preferred.Value}";
            }
            if (header.Length == 0 || header.Length > MaxBodyBytes)
            {
                await WriteResponseAsync(stream, 422, "没有收到可用的站点 Cookie 或网页会话。", cancellationToken);
                return;
            }

            lock (_gate)
            {
                if (ReferenceEquals(_pairing, pairing))
                    _pairing = pairing with { ExpiresAt = DateTimeOffset.UtcNow.AddMinutes(10) };
            }
            // Keep the short-lived pairing alive so the browser bridge can
            // upload newly captured usage responses during the next few
            // minutes. The code is still bound to one host/profile and
            // expires automatically; a later pairing replaces it.
            var rawUsageResponses = payload.UsageResponses?
                .Where(item => !string.IsNullOrWhiteSpace(item.Path) && item.Path.Length <= 256
                    && !string.IsNullOrWhiteSpace(item.Body) && item.Body.Length <= 384 * 1024)
                .Take(8)
                .ToArray() ?? Array.Empty<BridgeUsageResponse>();
            var authorization = payload.Authorization?.Trim() ?? "";
            var userId = payload.UserId?.Trim() ?? "";
            if (authorization.Length > 512 || authorization.Contains("\r", StringComparison.Ordinal) || authorization.Contains("\n", StringComparison.Ordinal))
                authorization = "";
            if (!authorization.StartsWith("Bearer ", StringComparison.OrdinalIgnoreCase))
                authorization = "";
            SessionReceived?.Invoke(this, new BrowserSessionReceivedEventArgs(
                pairing.ProfileId, pairing.SiteHost, header, authorization, userId, cookies.Length, storage.Length,
                rawUsageResponses.Select(item => new BrowserUsageResponse(item.Path, item.Body)).ToArray()));
            await WriteResponseAsync(stream, 200, $"浏览器会话已传递给 BalancePet（Cookie {cookies.Length} 项，网页会话 {storage.Length} 项，页面访问令牌 {(string.IsNullOrWhiteSpace(authorization) ? 0 : 1)} 项，页面捕获器 {(payload.CaptureInstalled ? "已安装" : "未安装")}，用量响应 {rawUsageResponses.Length} 项）。", cancellationToken);
        }
        catch (JsonException)
        {
            await WriteResponseAsync(stream, 400, "会话数据格式无效。", cancellationToken);
        }
        catch (OperationCanceledException) when (cancellationToken.IsCancellationRequested) { }
        catch (IOException) { }
        catch (ObjectDisposedException) { }
    }

    private static async Task<BridgeRequest?> ReadRequestAsync(NetworkStream stream, CancellationToken cancellationToken)
    {
        var buffer = new byte[8192];
        using var requestBuffer = new MemoryStream();
        var headerEnd = -1;
        while (requestBuffer.Length < MaxHeaderBytes)
        {
            var count = await stream.ReadAsync(buffer, cancellationToken);
            if (count == 0) return null;
            requestBuffer.Write(buffer, 0, count);
            var bytes = requestBuffer.ToArray();
            headerEnd = FindHeaderEnd(bytes);
            if (headerEnd >= 0) break;
        }
        if (headerEnd < 0) return null;
        var all = requestBuffer.ToArray();
        var headerText = Encoding.ASCII.GetString(all, 0, headerEnd);
        var firstLineEnd = headerText.IndexOf("\r\n", StringComparison.Ordinal);
        if (firstLineEnd <= 0) return null;
        var requestLine = headerText[..firstLineEnd].Split(' ', StringSplitOptions.RemoveEmptyEntries);
        if (requestLine.Length < 2) return null;
        var contentLength = 0;
        foreach (var line in headerText[(firstLineEnd + 2)..].Split("\r\n", StringSplitOptions.RemoveEmptyEntries))
        {
            var separator = line.IndexOf(':');
            if (separator <= 0) continue;
            if (line[..separator].Trim().Equals("Content-Length", StringComparison.OrdinalIgnoreCase))
                int.TryParse(line[(separator + 1)..].Trim(), out contentLength);
        }
        if (contentLength < 0 || contentLength > MaxBodyBytes) return null;
        var bodyStart = headerEnd + 4;
        while (all.Length - bodyStart < contentLength)
        {
            var count = await stream.ReadAsync(buffer, cancellationToken);
            if (count == 0) return null;
            requestBuffer.Write(buffer, 0, count);
            all = requestBuffer.ToArray();
        }
        var body = new byte[contentLength];
        Buffer.BlockCopy(all, bodyStart, body, 0, contentLength);
        return new BridgeRequest(requestLine[0], requestLine[1], body);
    }

    private static async Task WriteResponseAsync(NetworkStream stream, int status, string message, CancellationToken cancellationToken)
    {
        var body = JsonSerializer.SerializeToUtf8Bytes(new { ok = status is >= 200 and < 300, message });
        var reason = status switch { 200 => "OK", 204 => "No Content", 400 => "Bad Request", 403 => "Forbidden", 404 => "Not Found", 422 => "Unprocessable Entity", _ => "Error" };
        var header = $"HTTP/1.1 {status} {reason}\r\nContent-Type: application/json; charset=utf-8\r\nContent-Length: {body.Length}\r\nAccess-Control-Allow-Origin: *\r\nAccess-Control-Allow-Methods: POST, OPTIONS\r\nAccess-Control-Allow-Headers: content-type\r\nConnection: close\r\n\r\n";
        await stream.WriteAsync(Encoding.ASCII.GetBytes(header), cancellationToken);
        if (body.Length > 0) await stream.WriteAsync(body, cancellationToken);
    }
    private static bool HostMatches(string expected, string? actual)
    {
        var host = (actual ?? "").Trim().TrimStart('.').ToLowerInvariant();
        return host.Length > 0 && (host == expected || host.EndsWith("." + expected, StringComparison.Ordinal));
    }

    private static bool CryptographicEquals(string expected, string? actual)
    {
        if (actual is null || expected.Length != actual.Length) return false;
        var different = 0;
        for (var index = 0; index < expected.Length; index++) different |= expected[index] ^ actual[index];
        return different == 0;
    }

    private static int FindHeaderEnd(byte[] bytes)
    {
        for (var index = 0; index <= bytes.Length - 4; index++)
            if (bytes[index] == 13 && bytes[index + 1] == 10 && bytes[index + 2] == 13 && bytes[index + 3] == 10) return index;
        return -1;
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNameCaseInsensitive = true
    };

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        _shutdown.Cancel();
        lock (_gate) _pairing = null;
        try { _listener?.Stop(); } catch { }
        try { _acceptLoop?.Wait(TimeSpan.FromSeconds(1)); } catch { }
        _shutdown.Dispose();
    }

    private sealed record PairingState(string ProfileId, string SiteHost, string Code, DateTimeOffset ExpiresAt);
    private sealed record BridgeRequest(string Method, string Path, byte[] Body);
    private sealed record BridgePayload(string? Code, string? Host, IReadOnlyList<BridgeCookie>? Cookies, IReadOnlyList<BridgeStorageEntry>? Storage, IReadOnlyList<BridgeUsageResponse>? UsageResponses, string? Authorization, string? UserId, bool CaptureInstalled);
    private sealed record BridgeCookie(string Name, string Value);
    private sealed record BridgeStorageEntry(string Key, string Value);
    private sealed record BridgeUsageResponse(string Path, string Body);
}

public sealed record BrowserPairingInfo(string Code, string SiteHost, int Port, DateTimeOffset ExpiresAt);

public sealed class BrowserSessionReceivedEventArgs : EventArgs
{
    public BrowserSessionReceivedEventArgs(string profileId, string siteHost, string cookieHeader, string authorizationHeader, string userId, int cookieCount, int storageCount, IReadOnlyList<BrowserUsageResponse> usageResponses)
    {
        ProfileId = profileId;
        SiteHost = siteHost;
        CookieHeader = cookieHeader;
        AuthorizationHeader = authorizationHeader;
        UserId = userId;
        CookieCount = cookieCount;
        StorageCount = storageCount;
        UsageResponses = usageResponses;
    }

    public string ProfileId { get; }
    public string SiteHost { get; }
    public string CookieHeader { get; }
    public string AuthorizationHeader { get; }
    public string UserId { get; }
    public int CookieCount { get; }
    public int StorageCount { get; }
    public IReadOnlyList<BrowserUsageResponse> UsageResponses { get; }
}

public sealed record BrowserUsageResponse(string Path, string Body);
